### ISSUE TITLE
code question

### ISSUE THREAD

**Issue by aszhanghuali** [zhaoyinghe/DBN-python#1]
你好，代码能用来做肺结节的分类吗 ？@zhaoyinghe

**Comment by aszhanghuali** [comment]
@zhaoyinghe 你好，你能分享完整的代码嘛？我想用它做肺结节分类。
谢谢！期待你的回复！

**Comment by ZhaoyingAC** [comment]
@aszhanghuali DBN当时我是用来预训练模型参数用来初始化模型参数，当时效果并没有提升。如何你想做肺结节分类，可以直接使用传统机器学习分类模型以及深度学习分类模型。

**Comment by aszhanghuali** [comment]
> @aszhanghuali DBN当时我是用来预训练模型参数用来初始化模型参数，当时效果并没有提升。如何你想做肺结节分类，可以直接使用传统机器学习分类模型以及深度学习分类模型。

**Comment by aszhanghuali** [comment]
@zhaoyinghe 谢谢你的回复！
我现在研一，导师给的课题是用RBM/DBN来做。我本身没有学过计算机，所以比较着急。你有什么建议吗？

**Comment by aszhanghuali** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        您好！再次打扰到您！
        我想问您，您是怎么设置DBN模型参数的？或者说您是怎么进行参数调试的？我目前处理了部分数据，跑DBN分类代码，但测试集的准确率82%不是特别高，应该是参数不正确。能不能给我讲述一下您的调参思路？谢谢！期待您的回复！
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1319466165
                            
                    
                        
                            
                                    1319466165@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 3/14/2019 10:49，zhaoyinghe<notifications@github.com> wrote： 


@aszhanghuali DBN当时我是用来预训练模型参数用来初始化模型参数，当时效果并没有提升。如何你想做肺结节分类，可以直接使用传统机器学习分类模型以及深度学习分类模型。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
